### ISSUE TITLE
Seems that it does not work with OpenSSL 1.0.2g

### ISSUE THREAD

**Issue by kgizdov** [codexns/sublime-ssl-linux#4]
Hi,

On Arch Linux I am getting the following:

```
Package Control: Linux SSL: _ssl module import error - /home/gizdov/.config/sublime-text-3/Packages/ssl-linux/st3_linux_x64/libssl-1.0.0/_ssl.cpython-33m.so: symbol SSLv3_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference
Package Control: Linux SSL: _ssl module import error - libssl.so.10: cannot open shared object file: No such file or directory
Package Control: Linux SSL: _ssl module import error - libssl.so.0.9.8: cannot open shared object file: No such file or directory
```

I'm guessing something has changed and _ssl.cpython-33m.so doesn't like it. Can you confirm?

**Comment by zopsi** [comment]
I was able to temporarily fix this by symlinking the system lib and reinstalling package control. 

`ln -s /usr/lib64/python3.5/lib-dynload/_ssl.cpython-35m-x86_64-linux-gnu.so $HOME/.config/sublime-text-3/Packages/ssl-linux/st3_linux_x64/libssl-1.0.0/_ssl.cpython-33m.so`

There's probably a better way to do it, but I needed it fixed quickly.

**Comment by kgizdov** [comment]
Now I'm kinda thinking it might be a Python version issue. I had to symlink my Python 3.5 lib to make it work. I currently have this:

```
/home/$USER/.config/sublime-text-3/Packages/ssl-linux/st3_linux_x64/libssl-1.0.0/_ssl.cpython-33m.so -> /usr/lib/python3.5/lib-dynload/_ssl.cpython-35m-x86_64-linux-gnu.so
```

**Comment by sindrig** [comment]
This workaround did not work for me.

```
sindri->~ $ ls -l  ~/.config/sublime-text-3/Packages/ssl-linux/st3_linux_x64/libssl-1.0.0
total 204
lrwxrwxrwx 1 sindri sindri     67 17.03.2016 22:29 _ssl.cpython-33m.so -> /usr/lib/python3.5/lib-dynload/_ssl.cpython-35m-x86_64-linux-gnu.so*
-rw-r--r-- 1 sindri sindri 202753 15.03.2016 10:11 _ssl.cpython-33m.so.bak
```

And in sublime console:

```
>>> from package_control import sys_path
>>> dep_paths = sys_path.generate_dependency_paths(u'ssl-linux')
>>> sys_path.add(dep_paths['plat'], first=True)
>>> ssl_ver = u'1.0.0'
>>> lib_path = os.path.join(dep_paths['arch'], u'libssl-%s' % ssl_ver)
>>> lib_path
'/home/sindri/.config/sublime-text-3/Packages/ssl-linux/st3_linux_x64/libssl-1.0.0'
>>> sys_path.add(lib_path, first=True)
>>> import _ssl
>>> _ssl.__file__
'/home/sindri/.config/sublime-text-3/Packages/ssl-linux/st3_linux_x64/libssl-1.0.0/_ssl.cpython-33m.so'
>>> import ssl
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "./ssl.py", line 94, in <module>
ImportError: cannot import name PROTOCOL_SSLv3
```

**Comment by wbond** [comment]
Sorry, GitHub is dumb about notifications, so I didn't see this before now. Symlink to 3.5 def won't work, it would have to be from 3.3.

Hoping to have this fixed from within Sublime Text with the next dev build.

**Comment by sindrig** [comment]
Figured as much. At the moment this is a minor inconvenience so I'll monitor this thread for updates.

I've already written on the sublime forum regarding this issue but haven't gotten any response: https://forum.sublimetext.com/t/st-3-cannot-import-ssl/18506

**Comment by wbond** [comment]
As of ST3 build 3109 we bundle the latest version of 1.0.2 with Sublime Text itself.

This repo is effectively deprecated. If you are having trouble, I recommend grabbing the latest beta or dev build of ST3.
